default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/development.postgresql

test:
  <<: *default
  database: db/test.postgresql

production:
  <<: *default
  database: db/production.postgresql